# Generated by Django 2.2.3 on 2020-09-17 21:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Album', 'Album'), ('Riddim', 'Riddim'), ('Single', 'Single'), ('Cover', 'Cover')], max_length=500)),
                ('first_artist', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, null=True, unique=True)),
                ('file', models.ImageField(blank=True, upload_to='music/%y/%m/%d')),
                ('Paid', models.BooleanField(default=False)),
                ('allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Youtubefeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('video', models.URLField()),
                ('category', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Intertainment', 'Intertainment'), ('Food and Nutritions', 'Food and Nutritions'), ('Business', 'Business'), ('Others', 'Others')], default='Others', max_length=100)),
                ('Paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('House', 'House'), ('Hip Hop', 'Hip hop'), ('Trap', 'Trap'), ('Raggie', 'Raggie'), ('Amapiano', 'Amapiano'), ('Gospel', 'Gospel'), ('Beats', 'Beats'), ('Afro House', 'Afro House'), ('Dancehall', 'Dancehall'), ('Poetry', 'Poetry/Poem')], max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('sell', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('view', models.PositiveIntegerField(default=0)),
                ('topSeller', models.PositiveIntegerField(default=0)),
                ('artist', models.CharField(blank=True, max_length=500, null=True)),
                ('first_artist', models.BooleanField(default=False)),
                ('vote', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, null=True, unique=True)),
                ('Dicription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('free_music', models.BooleanField(default=False)),
                ('file', models.ImageField(blank=True, upload_to='music/%y/%m/%d')),
                ('mp3', models.FileField(blank=True, upload_to=music.models.upload_audio_location)),
                ('video', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paid', models.BooleanField(default=False)),
                ('allowed', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to='music.Album')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
