# Generated by Django 2.2.3 on 2020-09-17 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='Needed', max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('item2', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, null=True, unique=True)),
                ('view', models.BooleanField(default=False)),
                ('find', models.BooleanField(default=False)),
                ('found', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, upload_to='kunsika/%y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orderNo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
