# Generated by Django 2.2.3 on 2020-09-17 21:16

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Others', max_length=100)),
                ('file2', models.ImageField(blank=True, upload_to='brand')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('currency', models.CharField(default='MWK', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item_contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=500, null=True)),
                ('category2', models.CharField(blank=True, max_length=500, null=True)),
                ('brand2', models.CharField(blank=True, max_length=500, null=True)),
                ('item', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('topSeller', models.PositiveIntegerField(default=0)),
                ('top_rated', models.PositiveIntegerField(default=0)),
                ('sizes', models.CharField(blank=True, max_length=1000)),
                ('color', models.CharField(blank=True, max_length=1000)),
                ('district', models.CharField(blank=True, max_length=1000)),
                ('area', models.CharField(blank=True, max_length=1000)),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, null=True, unique=True)),
                ('Dicription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('allow_customer_buy_online', models.BooleanField(default=False)),
                ('file', models.ImageField(blank=True, upload_to='kunsika/%y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Paid', models.BooleanField(default=False)),
                ('timer', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='category_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dicription', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=products.models.upload_location2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='add_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='kunsika/%y/%m/%d')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.product')),
            ],
        ),
    ]
